owner: CristianPareja
repo: MonitorGHA2_CristianPareja

sites:
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://github.com
  - name: Sitio roto de prueba
    url: https://sitio-roto-prueba-123456789.com

status-website:
  baseUrl: /MonitorGHA2_CristianPareja
  name: Monitor CI/CD Cristian Pareja
  introTitle: "Página de monitoreo con Upptime"
  introMessage: "Este sitio monitorea servicios web usando GitHub Actions, Issues y GitHub Pages."
  navbar:
    - title: Estado
      href: /
    - title: Repositorio
      href: https://github.com/CristianPareja/MonitorGHA2_CristianPareja
